db.url=jdbc:mysql://localhost/trabalho_lpoo2
db.user=root
db.pwd=root
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


